FROM node:16-alpine AS hind-webpack-base

RUN mkdir /code
WORKDIR /code

COPY package.json package-lock.json /code/
RUN npm install
COPY webpack.config.js babel.config.js tsconfig.json .eslintrc.js /code/